# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Documents\newRoomDialogDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newRoomDialog(object):
    def setupUi(self, newRoomDialog):
        newRoomDialog.setObjectName("newRoomDialog")
        newRoomDialog.setEnabled(True)
        newRoomDialog.resize(174, 119)
        newRoomDialog.setSizeGripEnabled(False)
        newRoomDialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(newRoomDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sizeGroupBox = QtWidgets.QGroupBox(newRoomDialog)
        self.sizeGroupBox.setObjectName("sizeGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.sizeGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.widthSpinBox = QtWidgets.QSpinBox(self.sizeGroupBox)
        self.widthSpinBox.setMinimum(100)
        self.widthSpinBox.setMaximum(10000)
        self.widthSpinBox.setSingleStep(10)
        self.widthSpinBox.setProperty("value", 700)
        self.widthSpinBox.setObjectName("widthSpinBox")
        self.gridLayout.addWidget(self.widthSpinBox, 1, 0, 1, 1)
        self.heightSpinBox = QtWidgets.QSpinBox(self.sizeGroupBox)
        self.heightSpinBox.setMinimum(100)
        self.heightSpinBox.setMaximum(10000)
        self.heightSpinBox.setSingleStep(10)
        self.heightSpinBox.setProperty("value", 500)
        self.heightSpinBox.setObjectName("heightSpinBox")
        self.gridLayout.addWidget(self.heightSpinBox, 1, 1, 1, 1)
        self.widthLabel = QtWidgets.QLabel(self.sizeGroupBox)
        self.widthLabel.setObjectName("widthLabel")
        self.gridLayout.addWidget(self.widthLabel, 0, 0, 1, 1)
        self.heightLabel = QtWidgets.QLabel(self.sizeGroupBox)
        self.heightLabel.setObjectName("heightLabel")
        self.gridLayout.addWidget(self.heightLabel, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.sizeGroupBox)
        self.acceptBtn = QtWidgets.QPushButton(newRoomDialog)
        self.acceptBtn.setObjectName("acceptBtn")
        self.verticalLayout.addWidget(self.acceptBtn)

        self.retranslateUi(newRoomDialog)
        QtCore.QMetaObject.connectSlotsByName(newRoomDialog)

    def retranslateUi(self, newRoomDialog):
        _translate = QtCore.QCoreApplication.translate
        newRoomDialog.setWindowTitle(_translate("newRoomDialog", "Новая комната"))
        self.sizeGroupBox.setTitle(_translate("newRoomDialog", "Размер"))
        self.widthLabel.setText(_translate("newRoomDialog", "Ширина:"))
        self.heightLabel.setText(_translate("newRoomDialog", "Высота:"))
        self.acceptBtn.setText(_translate("newRoomDialog", "OK"))
